name: Deploy to Heroku

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 23.x
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Build the app
      run: yarn build

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: kapclear-fadil
        HEROKU_APP_URL: https://kapclear-fadil.herokuapp.com
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku container:login
        heroku container:push web --app kapclear-fadil
        heroku container:release web --app kapclear-fadil
